# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LensTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseLogin

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'SwiftLint'
pod 'FlagKit'
pod 'lottie-ios'
# pod 'AlertToast'




end
